### ISSUE TITLE
Old Google SDK

### ISSUE THREAD

**Issue by skoften** [jpriebe/ti.dfp#10]
An update would be great :-)

<Google:HTML> You are currently using version 6.12.2 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 7.1.0, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.

**Comment by jpriebe** [comment]
See version 1.1.3 for an update to the SDK

**Comment by skoften** [comment]
nice, thanks!
