### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by hgani** [jpriebe/ti.dfp#18]
Hi,

I got this exception when using calling ti.dfp's createView() on Android

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/doubleclick/PublisherAdView

I assume this is because we are meant to include the native DFP SDK's jar ourselves? If so, which directory should put the jar? I can't find anything in ti.dfp doc/readme.

Thanks

**Comment by jpriebe** [comment]
The jar is included in the plugin (in the lib directory).

Maybe something in your build process is including an older jar file and excluding the one used by the ti.dfp module?

**Comment by hgani** [comment]
@jpriebe Thanks for the quick response.

I could only see google-play-services.jar in lib/ directory. Is this the jar that contains the DFP SDK?

**Comment by jpriebe** [comment]
Yes.  All DFP mobile app functionality is part of google play services.

**Comment by hgani** [comment]
@jpriebe You're exactly right. 

For some reason, the lib/ directory did not get copied to my project and yes, it picked up the google play services jars from ti.map instead

Thanks
