### ISSUE TITLE
Create View is causing app to crash

### ISSUE THREAD

**Issue by AndreB10** [jpriebe/ti.dfp#9]
Hi,

I am using your app.js example and when I call createView I am getting the following error: 

"Could not find class 'com.google.android.gms.ads.doubleclick.PublisherAdView', referenced from method ti.dfp.View.createView"

Can I get some help, please?

Here is a more complete log:

[ERROR] :  dalvikvm: Could not find class 'com.google.android.gms.ads.doubleclick.PublisherAdView', referenced from method ti.dfp.View.createView
[WARN] :   dalvikvm: VFY: unable to resolve new-instance 1490 (Lcom/google/android/gms/ads/doubleclick/PublisherAdView;) in Lti/dfp/View;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.doubleclick.PublisherAdView.destroy, referenced from method ti.dfp.View.destroy
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 11694: Lcom/google/android/gms/ads/doubleclick/PublisherAdView;.destroy ()V
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.doubleclick.PublisherAdView.pause, referenced from method ti.dfp.View.pause
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 11698: Lcom/google/android/gms/ads/doubleclick/PublisherAdView;.pause ()V
[ERROR] :  dalvikvm: Could not find class 'com.google.android.gms.ads.AdSize[]', referenced from method ti.dfp.View.processProperties
[WARN] :   dalvikvm: VFY: unable to resolve new-array 3021 ([Lcom/google/android/gms/ads/AdSize;) in Lti/dfp/View;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.doubleclick.PublisherAdView.resume, referenced from method ti.dfp.View.resume
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 11699: Lcom/google/android/gms/ads/doubleclick/PublisherAdView;.resume ()V
[WARN] :   dalvikvm: Unable to resolve superclass of Lti/dfp/View$1; (1486)
[WARN] :   dalvikvm: Link of class 'Lti/dfp/View$1;' failed
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x1543 at 0x109 in Lti/dfp/View;.createView
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x413ea9a8)
[ERROR] :  TiApplication: (main) [0,28255] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.google.android.gms.ads.doubleclick.PublisherAdView; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: com.google.android.gms.ads.doubleclick.PublisherAdView

**Comment by jpriebe** [comment]
Sounds like the device you're running on does not have google play services.

**Comment by AndreB10** [comment]
Actually it does. It was an issue with the Android SDK. A fresh 
reinstall solved it...

Thank you for the answer!

**Comment by jpriebe** [comment]
Man, I *hate* when stuff like that happens (seems to happen all too often with Titanium + Android SDK)!  Glad you got it worked out.
